var language = {
//word: "translation",
  alas: "â",
  bind: "aʾālu",
  grandfather: "ab abi",
  lead: "abāku",
  dry: "ablu",
  dried: "abalu",
  arid: "ablu",
  hay: "ablūtu",
  sea: "abamātu",
  alum: "aban gabe",
  love0charm: "aban rāmi",
  date0stone: "aban suluppi",
  snake0stone: "aban ṣerru",
  mountain0rock: "aban šaddî",
  hailstone: "aban šamê*",
  leaden: "abārāiu+",
  lead0gray: "abārāiu+",
  livid: "abārāiu+",
  drab: "abārāiu+",
};
