var translate = (str) => {
  let language = {
    //word: "translation",
    translate0at0home: "abrakkūtu",
    alas: "â",
    bind: "aʾālu",
    grandfather: "ab abi",
    lead: "abāku",
    dry: "ablu",
    dried: "abalu",
    arid: "ablu",
    hay: "ablūtu",
    sea: "abamātu",
    alum: "aban gabe",
    love0charm: "aban rāmi",
    date0stone: "aban suluppi",
    snake0stone: "aban ṣerru",
    mountain0rock: "aban šadd",
    hailstone: "aban šamê*",
    leaden: "abārāiu+",
    lead0gray: "abārāiu+",
    livid: "abārāiu+",
    drab: "abārāiu+",
    stewardess: "abarakkatu",
    housekeeper: "abarakkatu",
    courtesan: "abarakkatu",
    steward: "abarakku",
    administrator: "abarakku",
    treasurer: "abarakku",
    high0state0official: "abarakku",
    chief0steward: "abarakku rabû",
    high0chamberlain: "abarakku rabû",
    truly: "abaraša",
    certainly: "abaraša",
    clamp: "abāru",
    embrace: "abāru",
    strength: "abāru",
    energy: "abāru",
    wrestler: "abāru",
    magic: "abāru",
    arms: "abāru",
    persons: "abāru",
    stars: "abāru",
    embrace0intensley: "abāru",
    /* bind: "abāru", */
    accuse: "abāru",
    denounce: "abāru",
    /* lead: "abāru", */
    lead0courtyard: "kisal abāri",
    water: "abasigga",
    land0surveyor0team: "abašlu",
    moonstone: "abašmu",
    gravel: "abattu",
    pestle: "abattu",
    irrigation0pipe: "abattu",
    stone0of0carab0bean: "abatti",
    abandon: "abātu",
    flee: "abātu",
    run0away: "abātu",
    escape: "abātu",
    desert: "abātu",
    paternity: "abbūtu",
    fatherhood: "abbūtu",
    father: "abbūtu",
    slingstone: "abattu",
    destroy: "abātu",
    collapse: "abātu",
    fall: "abātu",
    servant: "abdu",
    slave: "abdu",
    land0surveyor: "abi ašlim",
    defeat: "abiktu",
    turnip: "abīuru",
    cow: "abkigetu",
    cows: "abkigetu",
    drought: "ablūtu",
    rocky: "abnānu",
    precious0stone: "abnu mišil uqurtu *",
    magnet: "abnu ṣābittu *",
    stone: "abnu",
    rock: "abnu",
    gem: "abnu",
    mankind: "abrātu",
    humanity: "abrātu",
    populace: "abrātu",
    brushwood: "abriš",
  };
  for (let s = 0; s < count; s++) {
    var cipher = '';
    for (let i = 0; i < str.length; i++) {
      cipher += coded[str[i]];
    }
    str = cipher;
  }
  return str;
};
